CREATE TABLE DOCTOR (
       ID VARCHAR(50) NOT NULL,
       NAME VARCHAR(20) NOT NULL,
       HOSPITAL VARCHAR(20),
       DEGREE VARCHAR(10) NOT NULL,
       SPECIALIST VARCHAR(10),
       ADDRESS VARCHAR(100),
       MOBILE VARCHAR(10),
       APPONPHONE VARCHAR(12),
       ISEMAILSEND BOOLEAN,
       ISSMSSEND BOOLEAN,
       ISACTIVE BOOLEAN,
       CREATIONTIME TIMESTAMP,
       LASTMODIFIEDTIME TIMESTAMP,
       PRIMARY KEY(ID)
);